# Generated by Django 3.2.16 on 2023-01-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20230109_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')], default='public', max_length=9),
        ),
    ]
