# Generated by Django 3.2.16 on 2023-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_idea_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=8),
        ),
    ]
